name: Composite Action Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Run Composite Action
        uses: Revanth-Velugoti/composite_actions_repo@main
